import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import 'animate.css';
import { Toaster } from "react-hot-toast";

const poppins = Poppins({ 
  weight: ['400', '600', '700'], 
  subsets: ['latin'],
})

export const metadata = {
  title: "Livestock Booking Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body>
        <Navbar></Navbar>
        <main className="max-w-7xl mx-auto">
          {children}
        </main>
         <Toaster />
        <Footer></Footer>
        </body>
    </html>
  );
}
